### ISSUE TITLE
"six" is missing from the installation requirements

### ISSUE THREAD

**Issue by PatWalters** [plinder-org/plinder#31]
"pip install ." failed.  I was able to fix this with "pip install six".  

<pre>
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-idfp_634/oddt_b07b587cfb8d43389fcfd169d9bf418a/setup.py", line 3, in <module>
          from oddt import __version__ as VERSION
        File "/tmp/pip-install-idfp_634/oddt_b07b587cfb8d43389fcfd169d9bf418a/oddt/__init__.py", line 17, in <module>
          import six
      ModuleNotFoundError: No module named 'six'
      [end of output]
</pre>

**Comment by OleinikovasV** [comment]
@PatWalters , please try commenting out this line (oddt):
https://github.com/plinder-org/plinder/blob/main/pyproject.toml#L23

**Comment by naefl** [comment]
thanks for the report @PatWalters, for posterity - we're currently working on slimming down some of the dependencies and breaking it down into subpackages to work around `openstructure` install hassles
