### ISSUE TITLE
holo_structures from PlinderSystem

### ISSUE THREAD

**Issue by maciejwisniewski-drugdiscovery** [plinder-org/plinder#71]
Hi,
I am trying to recreate the example from your Documentary and I reach some problems, with .holo_structure

```
holo = plinder_system.holo_structure
Traceback (most recent call last):
  File "/storage/home/maciej.wisniewski/miniconda3/envs/dataset_builders/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-c8e1e8f6623a>", line 1, in <module>
    holo = plinder_system.holo_structure
AttributeError: 'PlinderSystem' object has no attribute 'holo_structure'
```

**Comment by maciejwisniewski-drugdiscovery** [comment]
Nvm, wrong version
